// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamlStyleTypes
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CommandVisisiblityString = "c286424e-bfbb-435f-931c-271a46525c61";
        public static Guid CommandVisisiblity = new Guid(CommandVisisiblityString);

        public const string XamlStyleTypesString = "f6e92971-6da4-4456-92ba-19120ac5ae3c";
        public static Guid XamlStyleTypes = new Guid(XamlStyleTypesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}