// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamlStyleTypes
{
    internal sealed partial class Vsix
    {
        public const string Id = "XamlStyleTypes.2ba01d12-6fe6-4f3f-9b6e-7d3e79b071bd";
        public const string Name = "XamlStyleTypes";
        public const string Description = @"Create types (classes) from explicitly defined XAML Styles.";
        public const string Language = "en-US";
        public const string Version = "0.1.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "MAUI; XAML";
    }
}
