/// <auto-generated>
/// This files was generated by MauiStyleGenerator
/// learn more at https://github.com/mrlacey/XamlStyleTypes
/// </auto-generated>


namespace SampleMauiApp.Resources.Styles
{
    public static partial class AppColors
    { 
        public const string Primary = "Primary";
        public const string Secondary = "Secondary";
        public const string Tertiary = "Tertiary";
        public const string White = "White";
        public const string Black = "Black";
        public const string Gray100 = "Gray100";
        public const string Gray200 = "Gray200";
        public const string Gray300 = "Gray300";
        public const string Gray400 = "Gray400";
        public const string Gray500 = "Gray500";
        public const string Gray600 = "Gray600";
        public const string Gray900 = "Gray900";
        public const string Gray950 = "Gray950";
        public const string Yellow100Accent = "Yellow100Accent";
        public const string Yellow200Accent = "Yellow200Accent";
        public const string Yellow300Accent = "Yellow300Accent";
        public const string Cyan100Accent = "Cyan100Accent";
        public const string Cyan200Accent = "Cyan200Accent";
        public const string Cyan300Accent = "Cyan300Accent";
        public const string Blue100Accent = "Blue100Accent";
        public const string Blue200Accent = "Blue200Accent";
        public const string Blue300Accent = "Blue300Accent";
    }

    public static partial class AppBrushes 
    { 
        public const string PrimaryBrush = "PrimaryBrush";
        public const string SecondaryBrush = "SecondaryBrush";
        public const string TertiaryBrush = "TertiaryBrush";
        public const string WhiteBrush = "WhiteBrush";
        public const string BlackBrush = "BlackBrush";
        public const string Gray100Brush = "Gray100Brush";
        public const string Gray200Brush = "Gray200Brush";
        public const string Gray300Brush = "Gray300Brush";
        public const string Gray400Brush = "Gray400Brush";
        public const string Gray500Brush = "Gray500Brush";
        public const string Gray600Brush = "Gray600Brush";
        public const string Gray900Brush = "Gray900Brush";
        public const string Gray950Brush = "Gray950Brush";
    }

}

