/// <auto-generated>
/// This files was generated by MauiStyleGenerator
/// learn more at https://github.com/mrlacey/XamlStyleTypes
/// </auto-generated>


namespace SampleMauiApp.Resources.Styles
{

    public class Heading : Label
    {
        public Heading()
        {
            if (App.Current.Resources.TryGetValue("Heading", out object result))
            {
                this.Style = result as Style;
            }
        }
    }

    public class SubHeading : Label
    {
        public SubHeading()
        {
            if (App.Current.Resources.TryGetValue("SubHeading", out object result))
            {
                this.Style = result as Style;
            }
        }
    }
}

